#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/export_module.py
========================
CPP-Compat C++20 Module Exporter Script

Responsibilities:
1. Takes the unified single-header `dist/compat.hpp` (or automatically runs
   `scripts/bundle_header.py` if missing).
2. Converts and packages it into a standard C++20 Module Interface Unit `dist/compat.ixx`.
3. Places standard headers and configuration directives in the Global Module Fragment:
     module;
     #include <...>
     export module compat;
4. Transforms `namespace compat` blocks into:
     export namespace compat { ... }
   so all shim functions, types, and templates are cleanly exported.
5. Retains XML documentation comments (/// <summary>, etc.) and regular comments.
6. Enforces UTF-8 BOM encoding for the output file `dist/compat.ixx`.
"""

import os
import sys
import re
import argparse
from pathlib import Path

# Import bundle functionality from sibling script
sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    import bundle_header
except ImportError:
    bundle_header = None


RE_PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\b')
RE_INCLUDE_EXTERNAL = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
RE_NAMESPACE_COMPAT = re.compile(r'^(?P<indent>\s*)namespace\s+compat\b(?!\s*::)(?P<rest>.*)$')
RE_NAMESPACE_COMPAT_DETAIL = re.compile(r'^(?P<indent>\s*)namespace\s+compat::detail\b(?P<rest>.*)$')


def find_repo_root(start_path: Path) -> Path:
    """Find repository root by looking for RULES.md, ARCHITECTURE.md, or .git."""
    curr = start_path.resolve()
    for _ in range(10):
        if (curr / "RULES.md").exists() or (curr / "ARCHITECTURE.md").exists() or (curr / ".git").exists():
            return curr
        if curr.parent == curr:
            break
        curr = curr.parent
    return start_path.resolve()


def convert_to_module(header_content: str, verbose: bool = False) -> str:
    """
    Transforms single-header content into a C++20 Module Interface Unit:
    - Global Module Fragment (GMF) holds STL includes and macros
    - export module compat;
    - export namespace compat { ... }
    """
    lines = header_content.splitlines()

    gmf_lines: list[str] = []
    purview_lines: list[str] = []

    # State machine:
    # Everything before the first namespace compat or class/struct/function definition
    # that consists of includes and macros belongs in GMF.
    in_gmf = True

    for line in lines:
        stripped = line.strip()

        # Pragma once is not used in module interface units
        if RE_PRAGMA_ONCE.match(stripped):
            continue

        # Check if we encounter the first namespace definition or code
        if in_gmf:
            if stripped.startswith("namespace compat") or stripped.startswith("template") or stripped.startswith("class ") or stripped.startswith("struct "):
                in_gmf = False

        if in_gmf:
            # We are in the Global Module Fragment
            gmf_lines.append(line)
        else:
            # In C++20 module purview, textual #include of standard headers is prohibited
            # All standard headers are included in the Global Module Fragment (GMF).
            m_inc = RE_INCLUDE_EXTERNAL.match(stripped)
            if m_inc:
                # Omit textual inclusion in module purview to avoid C5244
                continue

            # Transform "namespace compat" into "export namespace compat"
            m_ns = RE_NAMESPACE_COMPAT.match(line)
            m_ns_detail = RE_NAMESPACE_COMPAT_DETAIL.match(line)
            if m_ns:
                indent = m_ns.group("indent")
                rest = m_ns.group("rest")
                purview_lines.append(f"{indent}export namespace compat{rest}")
            elif m_ns_detail:
                indent = m_ns_detail.group("indent")
                rest = m_ns_detail.group("rest")
                purview_lines.append(f"{indent}export namespace compat::detail{rest}")
            else:
                purview_lines.append(line)

    # Clean blank lines in GMF and purview
    def strip_outer_blanks(lst: list[str]) -> list[str]:
        while lst and lst[0].strip() == "":
            lst.pop(0)
        while lst and lst[-1].strip() == "":
            lst.pop()
        return lst

    gmf_lines = strip_outer_blanks(gmf_lines)
    purview_lines = strip_outer_blanks(purview_lines)

    result_parts: list[str] = []

    # Module banner
    result_parts.append("// ============================================================================")
    result_parts.append("// CPP-Compat: Zero-Dependency Modern C++ Backward Compatibility Shim Layer")
    result_parts.append("// C++20 Module Interface Unit (dist/compat.ixx)")
    result_parts.append("//")
    result_parts.append("// This file is automatically generated by scripts/export_module.py.")
    result_parts.append("// Do not edit this file directly.")
    result_parts.append("// ============================================================================")
    result_parts.append("")
    result_parts.append("module;")
    result_parts.append("")

    if gmf_lines:
        result_parts.append("// ----------------------------------------------------------------------------")
        result_parts.append("// Global Module Fragment (GMF): Preprocessor Directives & Standard Headers")
        result_parts.append("// ----------------------------------------------------------------------------")
        result_parts.extend(gmf_lines)
        result_parts.append("")
        result_parts.append("// Conditional Standard Headers for C++20 / C++23 in GMF")
        result_parts.append("#if defined(__has_include)")
        result_parts.append("#  if __has_include(<string_view>)")
        result_parts.append("#    include <string_view>")
        result_parts.append("#  endif")
        result_parts.append("#  if __has_include(<format>)")
        result_parts.append("#    include <format>")
        result_parts.append("#  endif")
        result_parts.append("#  if __has_include(<expected>)")
        result_parts.append("#    include <expected>")
        result_parts.append("#  endif")
        result_parts.append("#  if __has_include(<print>)")
        result_parts.append("#    include <print>")
        result_parts.append("#  endif")
        result_parts.append("#endif")
        result_parts.append("")

    result_parts.append("// ============================================================================")
    result_parts.append("// Module Purview: compat")
    result_parts.append("// ============================================================================")
    result_parts.append("export module compat;")
    result_parts.append("")

    if purview_lines:
        result_parts.extend(purview_lines)
        result_parts.append("")

    result_parts.append("// ============================================================================")
    result_parts.append("// End of C++20 Module Interface Unit: dist/compat.ixx")
    result_parts.append("// ============================================================================")
    result_parts.append("")

    return "\n".join(result_parts)


def export_module(input_header: Path, output_ixx: Path, verbose: bool = False) -> Path:
    """Main export function."""
    repo_root = find_repo_root(input_header.parent)
    if not input_header.is_absolute():
        input_header = (repo_root / input_header).resolve()
    if not output_ixx.is_absolute():
        output_ixx = (repo_root / output_ixx).resolve()

    # If input header does not exist, try bundling it first
    if not input_header.exists():
        if verbose:
            print(f"[INFO] '{input_header}' not found. Attempting to bundle from include/compat...")
        compat_dir = repo_root / "include" / "compat"
        if bundle_header and compat_dir.exists():
            bundle_header.bundle(compat_dir, input_header, verbose=verbose)
        else:
            raise FileNotFoundError(f"Cannot generate module: input header '{input_header}' does not exist and cannot be bundled.")

    with open(input_header, "r", encoding="utf-8-sig", errors="replace") as f:
        header_content = f.read()

    module_content = convert_to_module(header_content, verbose=verbose)

    # Ensure output directory exists
    output_ixx.parent.mkdir(parents=True, exist_ok=True)

    # Write output with UTF-8 BOM
    with open(output_ixx, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(module_content)

    # Verify UTF-8 BOM
    raw_bytes = output_ixx.read_bytes()
    assert raw_bytes.startswith(b"\xef\xbb\xbf"), "Error: Output module does not contain UTF-8 BOM!"

    line_count = len(module_content.splitlines())
    byte_count = len(raw_bytes)
    print(f"[SUCCESS] C++20 Module Interface Unit generated: {output_ixx} ({line_count} lines, {byte_count} bytes, UTF-8 BOM verified)")
    return output_ixx


def main():
    parser = argparse.ArgumentParser(description="CPP-Compat C++20 Module Exporter")
    parser.add_argument(
        "--input", "-i",
        type=str,
        default="dist/compat.hpp",
        help="Path to single-header dist/compat.hpp (default: dist/compat.hpp)"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="dist/compat.ixx",
        help="Path to output module unit (default: dist/compat.ixx)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable detailed diagnostic logging"
    )

    args = parser.parse_args()
    script_dir = Path(__file__).resolve().parent
    repo_root = find_repo_root(script_dir)

    input_path = Path(args.input)
    if not input_path.is_absolute():
        input_path = repo_root / input_path

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = repo_root / output_path

    try:
        export_module(input_path, output_path, verbose=args.verbose)
    except Exception as e:
        sys.stderr.write(f"[ERROR] Module export failed: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
